/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatWeOfferRouteImport } from './routes/what-we-offer'
import { Route as WellbeingRouteImport } from './routes/wellbeing'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app/index'
import { Route as AuthenticatedAppWorkoutsRouteImport } from './routes/_authenticated/app/workouts'
import { Route as AuthenticatedAppRewardsRouteImport } from './routes/_authenticated/app/rewards'
import { Route as AuthenticatedAppProgressRouteImport } from './routes/_authenticated/app/progress'
import { Route as AuthenticatedAppProfileRouteImport } from './routes/_authenticated/app/profile'
import { Route as AuthenticatedAppPartnerRouteImport } from './routes/_authenticated/app/partner'
import { Route as AuthenticatedAppNutritionRouteImport } from './routes/_authenticated/app/nutrition'
import { Route as AuthenticatedAppLeaderboardRouteImport } from './routes/_authenticated/app/leaderboard'
import { Route as AuthenticatedAppHabitsRouteImport } from './routes/_authenticated/app/habits'
import { Route as AuthenticatedAppCommunityRouteImport } from './routes/_authenticated/app/community'
import { Route as AuthenticatedAppCoachRouteImport } from './routes/_authenticated/app/coach'
import { Route as AuthenticatedAppChallengesRouteImport } from './routes/_authenticated/app/challenges'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app/ai'
import { Route as AuthenticatedAcceptInviteCodeRouteImport } from './routes/_authenticated/accept-invite.$code'
import { Route as ApiPublicHooksWeeklyRecapRouteImport } from './routes/api/public/hooks/weekly-recap'
import { Route as ApiPublicHooksSyncOauthDevicesRouteImport } from './routes/api/public/hooks/sync-oauth-devices'
import { Route as ApiPublicHooksSyncGoogleFitRouteImport } from './routes/api/public/hooks/sync-google-fit'
import { Route as ApiPublicHooksStreakAtRiskAlertRouteImport } from './routes/api/public/hooks/streak-at-risk-alert'
import { Route as ApiPublicHooksSendRemindersRouteImport } from './routes/api/public/hooks/send-reminders'
import { Route as ApiPublicHooksScoreRecomputeRouteImport } from './routes/api/public/hooks/score-recompute'
import { Route as ApiPublicHooksDailyMissionsGenerateRouteImport } from './routes/api/public/hooks/daily-missions-generate'
import { Route as ApiPublicHooksAutoMatchPartnersRouteImport } from './routes/api/public/hooks/auto-match-partners'
import { Route as ApiPublicGoogleFitCallbackRouteImport } from './routes/api/public/google-fit/callback'
import { Route as AuthenticatedAppUUserIdRouteImport } from './routes/_authenticated/app/u.$userId'
import { Route as ApiPublicOauthProviderCallbackRouteImport } from './routes/api/public/oauth/$provider.callback'

const WhatWeOfferRoute = WhatWeOfferRouteImport.update({
  id: '/what-we-offer',
  path: '/what-we-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const WellbeingRoute = WellbeingRouteImport.update({
  id: '/wellbeing',
  path: '/wellbeing',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppWorkoutsRoute =
  AuthenticatedAppWorkoutsRouteImport.update({
    id: '/workouts',
    path: '/workouts',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppRewardsRoute = AuthenticatedAppRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppProgressRoute =
  AuthenticatedAppProgressRouteImport.update({
    id: '/progress',
    path: '/progress',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppProfileRoute = AuthenticatedAppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPartnerRoute = AuthenticatedAppPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppNutritionRoute =
  AuthenticatedAppNutritionRouteImport.update({
    id: '/nutrition',
    path: '/nutrition',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppLeaderboardRoute =
  AuthenticatedAppLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHabitsRoute = AuthenticatedAppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCommunityRoute =
  AuthenticatedAppCommunityRouteImport.update({
    id: '/community',
    path: '/community',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCoachRoute = AuthenticatedAppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppChallengesRoute =
  AuthenticatedAppChallengesRouteImport.update({
    id: '/challenges',
    path: '/challenges',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAcceptInviteCodeRoute =
  AuthenticatedAcceptInviteCodeRouteImport.update({
    id: '/accept-invite/$code',
    path: '/accept-invite/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksWeeklyRecapRoute =
  ApiPublicHooksWeeklyRecapRouteImport.update({
    id: '/api/public/hooks/weekly-recap',
    path: '/api/public/hooks/weekly-recap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncOauthDevicesRoute =
  ApiPublicHooksSyncOauthDevicesRouteImport.update({
    id: '/api/public/hooks/sync-oauth-devices',
    path: '/api/public/hooks/sync-oauth-devices',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSyncGoogleFitRoute =
  ApiPublicHooksSyncGoogleFitRouteImport.update({
    id: '/api/public/hooks/sync-google-fit',
    path: '/api/public/hooks/sync-google-fit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksStreakAtRiskAlertRoute =
  ApiPublicHooksStreakAtRiskAlertRouteImport.update({
    id: '/api/public/hooks/streak-at-risk-alert',
    path: '/api/public/hooks/streak-at-risk-alert',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRemindersRoute =
  ApiPublicHooksSendRemindersRouteImport.update({
    id: '/api/public/hooks/send-reminders',
    path: '/api/public/hooks/send-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksScoreRecomputeRoute =
  ApiPublicHooksScoreRecomputeRouteImport.update({
    id: '/api/public/hooks/score-recompute',
    path: '/api/public/hooks/score-recompute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailyMissionsGenerateRoute =
  ApiPublicHooksDailyMissionsGenerateRouteImport.update({
    id: '/api/public/hooks/daily-missions-generate',
    path: '/api/public/hooks/daily-missions-generate',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutoMatchPartnersRoute =
  ApiPublicHooksAutoMatchPartnersRouteImport.update({
    id: '/api/public/hooks/auto-match-partners',
    path: '/api/public/hooks/auto-match-partners',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGoogleFitCallbackRoute =
  ApiPublicGoogleFitCallbackRouteImport.update({
    id: '/api/public/google-fit/callback',
    path: '/api/public/google-fit/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAppUUserIdRoute = AuthenticatedAppUUserIdRouteImport.update({
  id: '/u/$userId',
  path: '/u/$userId',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const ApiPublicOauthProviderCallbackRoute =
  ApiPublicOauthProviderCallbackRouteImport.update({
    id: '/api/public/oauth/$provider/callback',
    path: '/api/public/oauth/$provider/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/wellbeing': typeof WellbeingRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/accept-invite/$code': typeof AuthenticatedAcceptInviteCodeRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/challenges': typeof AuthenticatedAppChallengesRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/habits': typeof AuthenticatedAppHabitsRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/api/public/google-fit/callback': typeof ApiPublicGoogleFitCallbackRoute
  '/api/public/hooks/auto-match-partners': typeof ApiPublicHooksAutoMatchPartnersRoute
  '/api/public/hooks/daily-missions-generate': typeof ApiPublicHooksDailyMissionsGenerateRoute
  '/api/public/hooks/score-recompute': typeof ApiPublicHooksScoreRecomputeRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/streak-at-risk-alert': typeof ApiPublicHooksStreakAtRiskAlertRoute
  '/api/public/hooks/sync-google-fit': typeof ApiPublicHooksSyncGoogleFitRoute
  '/api/public/hooks/sync-oauth-devices': typeof ApiPublicHooksSyncOauthDevicesRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/wellbeing': typeof WellbeingRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/accept-invite/$code': typeof AuthenticatedAcceptInviteCodeRoute
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/challenges': typeof AuthenticatedAppChallengesRoute
  '/app/coach': typeof AuthenticatedAppCoachRoute
  '/app/community': typeof AuthenticatedAppCommunityRoute
  '/app/habits': typeof AuthenticatedAppHabitsRoute
  '/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/app/partner': typeof AuthenticatedAppPartnerRoute
  '/app/profile': typeof AuthenticatedAppProfileRoute
  '/app/progress': typeof AuthenticatedAppProgressRoute
  '/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/api/public/google-fit/callback': typeof ApiPublicGoogleFitCallbackRoute
  '/api/public/hooks/auto-match-partners': typeof ApiPublicHooksAutoMatchPartnersRoute
  '/api/public/hooks/daily-missions-generate': typeof ApiPublicHooksDailyMissionsGenerateRoute
  '/api/public/hooks/score-recompute': typeof ApiPublicHooksScoreRecomputeRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/streak-at-risk-alert': typeof ApiPublicHooksStreakAtRiskAlertRoute
  '/api/public/hooks/sync-google-fit': typeof ApiPublicHooksSyncGoogleFitRoute
  '/api/public/hooks/sync-oauth-devices': typeof ApiPublicHooksSyncOauthDevicesRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/coach': typeof CoachRoute
  '/contact': typeof ContactRoute
  '/fitness': typeof FitnessRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/wellbeing': typeof WellbeingRoute
  '/what-we-offer': typeof WhatWeOfferRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/accept-invite/$code': typeof AuthenticatedAcceptInviteCodeRoute
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/challenges': typeof AuthenticatedAppChallengesRoute
  '/_authenticated/app/coach': typeof AuthenticatedAppCoachRoute
  '/_authenticated/app/community': typeof AuthenticatedAppCommunityRoute
  '/_authenticated/app/habits': typeof AuthenticatedAppHabitsRoute
  '/_authenticated/app/leaderboard': typeof AuthenticatedAppLeaderboardRoute
  '/_authenticated/app/nutrition': typeof AuthenticatedAppNutritionRoute
  '/_authenticated/app/partner': typeof AuthenticatedAppPartnerRoute
  '/_authenticated/app/profile': typeof AuthenticatedAppProfileRoute
  '/_authenticated/app/progress': typeof AuthenticatedAppProgressRoute
  '/_authenticated/app/rewards': typeof AuthenticatedAppRewardsRoute
  '/_authenticated/app/workouts': typeof AuthenticatedAppWorkoutsRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/u/$userId': typeof AuthenticatedAppUUserIdRoute
  '/api/public/google-fit/callback': typeof ApiPublicGoogleFitCallbackRoute
  '/api/public/hooks/auto-match-partners': typeof ApiPublicHooksAutoMatchPartnersRoute
  '/api/public/hooks/daily-missions-generate': typeof ApiPublicHooksDailyMissionsGenerateRoute
  '/api/public/hooks/score-recompute': typeof ApiPublicHooksScoreRecomputeRoute
  '/api/public/hooks/send-reminders': typeof ApiPublicHooksSendRemindersRoute
  '/api/public/hooks/streak-at-risk-alert': typeof ApiPublicHooksStreakAtRiskAlertRoute
  '/api/public/hooks/sync-google-fit': typeof ApiPublicHooksSyncGoogleFitRoute
  '/api/public/hooks/sync-oauth-devices': typeof ApiPublicHooksSyncOauthDevicesRoute
  '/api/public/hooks/weekly-recap': typeof ApiPublicHooksWeeklyRecapRoute
  '/api/public/oauth/$provider/callback': typeof ApiPublicOauthProviderCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coach'
    | '/contact'
    | '/fitness'
    | '/gallery'
    | '/login'
    | '/pricing'
    | '/wellbeing'
    | '/what-we-offer'
    | '/admin'
    | '/app'
    | '/dashboard'
    | '/onboarding'
    | '/api/chat'
    | '/accept-invite/$code'
    | '/app/ai'
    | '/app/challenges'
    | '/app/coach'
    | '/app/community'
    | '/app/habits'
    | '/app/leaderboard'
    | '/app/nutrition'
    | '/app/partner'
    | '/app/profile'
    | '/app/progress'
    | '/app/rewards'
    | '/app/workouts'
    | '/app/'
    | '/app/u/$userId'
    | '/api/public/google-fit/callback'
    | '/api/public/hooks/auto-match-partners'
    | '/api/public/hooks/daily-missions-generate'
    | '/api/public/hooks/score-recompute'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/streak-at-risk-alert'
    | '/api/public/hooks/sync-google-fit'
    | '/api/public/hooks/sync-oauth-devices'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/oauth/$provider/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coach'
    | '/contact'
    | '/fitness'
    | '/gallery'
    | '/login'
    | '/pricing'
    | '/wellbeing'
    | '/what-we-offer'
    | '/admin'
    | '/dashboard'
    | '/onboarding'
    | '/api/chat'
    | '/accept-invite/$code'
    | '/app/ai'
    | '/app/challenges'
    | '/app/coach'
    | '/app/community'
    | '/app/habits'
    | '/app/leaderboard'
    | '/app/nutrition'
    | '/app/partner'
    | '/app/profile'
    | '/app/progress'
    | '/app/rewards'
    | '/app/workouts'
    | '/app'
    | '/app/u/$userId'
    | '/api/public/google-fit/callback'
    | '/api/public/hooks/auto-match-partners'
    | '/api/public/hooks/daily-missions-generate'
    | '/api/public/hooks/score-recompute'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/streak-at-risk-alert'
    | '/api/public/hooks/sync-google-fit'
    | '/api/public/hooks/sync-oauth-devices'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/oauth/$provider/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/coach'
    | '/contact'
    | '/fitness'
    | '/gallery'
    | '/login'
    | '/pricing'
    | '/wellbeing'
    | '/what-we-offer'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/api/chat'
    | '/_authenticated/accept-invite/$code'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/challenges'
    | '/_authenticated/app/coach'
    | '/_authenticated/app/community'
    | '/_authenticated/app/habits'
    | '/_authenticated/app/leaderboard'
    | '/_authenticated/app/nutrition'
    | '/_authenticated/app/partner'
    | '/_authenticated/app/profile'
    | '/_authenticated/app/progress'
    | '/_authenticated/app/rewards'
    | '/_authenticated/app/workouts'
    | '/_authenticated/app/'
    | '/_authenticated/app/u/$userId'
    | '/api/public/google-fit/callback'
    | '/api/public/hooks/auto-match-partners'
    | '/api/public/hooks/daily-missions-generate'
    | '/api/public/hooks/score-recompute'
    | '/api/public/hooks/send-reminders'
    | '/api/public/hooks/streak-at-risk-alert'
    | '/api/public/hooks/sync-google-fit'
    | '/api/public/hooks/sync-oauth-devices'
    | '/api/public/hooks/weekly-recap'
    | '/api/public/oauth/$provider/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CoachRoute: typeof CoachRoute
  ContactRoute: typeof ContactRoute
  FitnessRoute: typeof FitnessRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  WellbeingRoute: typeof WellbeingRoute
  WhatWeOfferRoute: typeof WhatWeOfferRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiPublicGoogleFitCallbackRoute: typeof ApiPublicGoogleFitCallbackRoute
  ApiPublicHooksAutoMatchPartnersRoute: typeof ApiPublicHooksAutoMatchPartnersRoute
  ApiPublicHooksDailyMissionsGenerateRoute: typeof ApiPublicHooksDailyMissionsGenerateRoute
  ApiPublicHooksScoreRecomputeRoute: typeof ApiPublicHooksScoreRecomputeRoute
  ApiPublicHooksSendRemindersRoute: typeof ApiPublicHooksSendRemindersRoute
  ApiPublicHooksStreakAtRiskAlertRoute: typeof ApiPublicHooksStreakAtRiskAlertRoute
  ApiPublicHooksSyncGoogleFitRoute: typeof ApiPublicHooksSyncGoogleFitRoute
  ApiPublicHooksSyncOauthDevicesRoute: typeof ApiPublicHooksSyncOauthDevicesRoute
  ApiPublicHooksWeeklyRecapRoute: typeof ApiPublicHooksWeeklyRecapRoute
  ApiPublicOauthProviderCallbackRoute: typeof ApiPublicOauthProviderCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/what-we-offer': {
      id: '/what-we-offer'
      path: '/what-we-offer'
      fullPath: '/what-we-offer'
      preLoaderRoute: typeof WhatWeOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wellbeing': {
      id: '/wellbeing'
      path: '/wellbeing'
      fullPath: '/wellbeing'
      preLoaderRoute: typeof WellbeingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/workouts': {
      id: '/_authenticated/app/workouts'
      path: '/workouts'
      fullPath: '/app/workouts'
      preLoaderRoute: typeof AuthenticatedAppWorkoutsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/rewards': {
      id: '/_authenticated/app/rewards'
      path: '/rewards'
      fullPath: '/app/rewards'
      preLoaderRoute: typeof AuthenticatedAppRewardsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/progress': {
      id: '/_authenticated/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AuthenticatedAppProgressRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/profile': {
      id: '/_authenticated/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AuthenticatedAppProfileRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/partner': {
      id: '/_authenticated/app/partner'
      path: '/partner'
      fullPath: '/app/partner'
      preLoaderRoute: typeof AuthenticatedAppPartnerRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/nutrition': {
      id: '/_authenticated/app/nutrition'
      path: '/nutrition'
      fullPath: '/app/nutrition'
      preLoaderRoute: typeof AuthenticatedAppNutritionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/leaderboard': {
      id: '/_authenticated/app/leaderboard'
      path: '/leaderboard'
      fullPath: '/app/leaderboard'
      preLoaderRoute: typeof AuthenticatedAppLeaderboardRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/habits': {
      id: '/_authenticated/app/habits'
      path: '/habits'
      fullPath: '/app/habits'
      preLoaderRoute: typeof AuthenticatedAppHabitsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/community': {
      id: '/_authenticated/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AuthenticatedAppCommunityRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/coach': {
      id: '/_authenticated/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AuthenticatedAppCoachRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/challenges': {
      id: '/_authenticated/app/challenges'
      path: '/challenges'
      fullPath: '/app/challenges'
      preLoaderRoute: typeof AuthenticatedAppChallengesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/accept-invite/$code': {
      id: '/_authenticated/accept-invite/$code'
      path: '/accept-invite/$code'
      fullPath: '/accept-invite/$code'
      preLoaderRoute: typeof AuthenticatedAcceptInviteCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/weekly-recap': {
      id: '/api/public/hooks/weekly-recap'
      path: '/api/public/hooks/weekly-recap'
      fullPath: '/api/public/hooks/weekly-recap'
      preLoaderRoute: typeof ApiPublicHooksWeeklyRecapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-oauth-devices': {
      id: '/api/public/hooks/sync-oauth-devices'
      path: '/api/public/hooks/sync-oauth-devices'
      fullPath: '/api/public/hooks/sync-oauth-devices'
      preLoaderRoute: typeof ApiPublicHooksSyncOauthDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/sync-google-fit': {
      id: '/api/public/hooks/sync-google-fit'
      path: '/api/public/hooks/sync-google-fit'
      fullPath: '/api/public/hooks/sync-google-fit'
      preLoaderRoute: typeof ApiPublicHooksSyncGoogleFitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/streak-at-risk-alert': {
      id: '/api/public/hooks/streak-at-risk-alert'
      path: '/api/public/hooks/streak-at-risk-alert'
      fullPath: '/api/public/hooks/streak-at-risk-alert'
      preLoaderRoute: typeof ApiPublicHooksStreakAtRiskAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-reminders': {
      id: '/api/public/hooks/send-reminders'
      path: '/api/public/hooks/send-reminders'
      fullPath: '/api/public/hooks/send-reminders'
      preLoaderRoute: typeof ApiPublicHooksSendRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/score-recompute': {
      id: '/api/public/hooks/score-recompute'
      path: '/api/public/hooks/score-recompute'
      fullPath: '/api/public/hooks/score-recompute'
      preLoaderRoute: typeof ApiPublicHooksScoreRecomputeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-missions-generate': {
      id: '/api/public/hooks/daily-missions-generate'
      path: '/api/public/hooks/daily-missions-generate'
      fullPath: '/api/public/hooks/daily-missions-generate'
      preLoaderRoute: typeof ApiPublicHooksDailyMissionsGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/auto-match-partners': {
      id: '/api/public/hooks/auto-match-partners'
      path: '/api/public/hooks/auto-match-partners'
      fullPath: '/api/public/hooks/auto-match-partners'
      preLoaderRoute: typeof ApiPublicHooksAutoMatchPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/google-fit/callback': {
      id: '/api/public/google-fit/callback'
      path: '/api/public/google-fit/callback'
      fullPath: '/api/public/google-fit/callback'
      preLoaderRoute: typeof ApiPublicGoogleFitCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/u/$userId': {
      id: '/_authenticated/app/u/$userId'
      path: '/u/$userId'
      fullPath: '/app/u/$userId'
      preLoaderRoute: typeof AuthenticatedAppUUserIdRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/api/public/oauth/$provider/callback': {
      id: '/api/public/oauth/$provider/callback'
      path: '/api/public/oauth/$provider/callback'
      fullPath: '/api/public/oauth/$provider/callback'
      preLoaderRoute: typeof ApiPublicOauthProviderCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppChallengesRoute: typeof AuthenticatedAppChallengesRoute
  AuthenticatedAppCoachRoute: typeof AuthenticatedAppCoachRoute
  AuthenticatedAppCommunityRoute: typeof AuthenticatedAppCommunityRoute
  AuthenticatedAppHabitsRoute: typeof AuthenticatedAppHabitsRoute
  AuthenticatedAppLeaderboardRoute: typeof AuthenticatedAppLeaderboardRoute
  AuthenticatedAppNutritionRoute: typeof AuthenticatedAppNutritionRoute
  AuthenticatedAppPartnerRoute: typeof AuthenticatedAppPartnerRoute
  AuthenticatedAppProfileRoute: typeof AuthenticatedAppProfileRoute
  AuthenticatedAppProgressRoute: typeof AuthenticatedAppProgressRoute
  AuthenticatedAppRewardsRoute: typeof AuthenticatedAppRewardsRoute
  AuthenticatedAppWorkoutsRoute: typeof AuthenticatedAppWorkoutsRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppUUserIdRoute: typeof AuthenticatedAppUUserIdRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppChallengesRoute: AuthenticatedAppChallengesRoute,
  AuthenticatedAppCoachRoute: AuthenticatedAppCoachRoute,
  AuthenticatedAppCommunityRoute: AuthenticatedAppCommunityRoute,
  AuthenticatedAppHabitsRoute: AuthenticatedAppHabitsRoute,
  AuthenticatedAppLeaderboardRoute: AuthenticatedAppLeaderboardRoute,
  AuthenticatedAppNutritionRoute: AuthenticatedAppNutritionRoute,
  AuthenticatedAppPartnerRoute: AuthenticatedAppPartnerRoute,
  AuthenticatedAppProfileRoute: AuthenticatedAppProfileRoute,
  AuthenticatedAppProgressRoute: AuthenticatedAppProgressRoute,
  AuthenticatedAppRewardsRoute: AuthenticatedAppRewardsRoute,
  AuthenticatedAppWorkoutsRoute: AuthenticatedAppWorkoutsRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppUUserIdRoute: AuthenticatedAppUUserIdRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAcceptInviteCodeRoute: typeof AuthenticatedAcceptInviteCodeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAcceptInviteCodeRoute: AuthenticatedAcceptInviteCodeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CoachRoute: CoachRoute,
  ContactRoute: ContactRoute,
  FitnessRoute: FitnessRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  WellbeingRoute: WellbeingRoute,
  WhatWeOfferRoute: WhatWeOfferRoute,
  ApiChatRoute: ApiChatRoute,
  ApiPublicGoogleFitCallbackRoute: ApiPublicGoogleFitCallbackRoute,
  ApiPublicHooksAutoMatchPartnersRoute: ApiPublicHooksAutoMatchPartnersRoute,
  ApiPublicHooksDailyMissionsGenerateRoute:
    ApiPublicHooksDailyMissionsGenerateRoute,
  ApiPublicHooksScoreRecomputeRoute: ApiPublicHooksScoreRecomputeRoute,
  ApiPublicHooksSendRemindersRoute: ApiPublicHooksSendRemindersRoute,
  ApiPublicHooksStreakAtRiskAlertRoute: ApiPublicHooksStreakAtRiskAlertRoute,
  ApiPublicHooksSyncGoogleFitRoute: ApiPublicHooksSyncGoogleFitRoute,
  ApiPublicHooksSyncOauthDevicesRoute: ApiPublicHooksSyncOauthDevicesRoute,
  ApiPublicHooksWeeklyRecapRoute: ApiPublicHooksWeeklyRecapRoute,
  ApiPublicOauthProviderCallbackRoute: ApiPublicOauthProviderCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
